In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import average_precision_score

In [2]:
data = pd.read_excel('Book1.xlsx')
data

,MRN,Nationality,Age,DATE OF BIRTH,Gender,COVID-19 Status \n(Positive),Date of Hospital Admission \nMM/DD/YYYY hh:mm,Date of ICU Admission \nMM/DD/YYYY hh:mm,Non Invasive Positive Pressure Ventilation (NIPPV),Mechanical Ventilation,...,Renal Replacement Therapy (Dialysis) in ICU,Chronic Cardiovascular-Lung Disease,Chronic Liver Kidney Disease,Diabetes,Hypertension,Any other Risk Factors or Comorbidities?,"If previous question is Yes, Specify:",ICU Outcome,Date of Outcome\nMM/DD/YYYY,ICU LOS
0,1089121,Sudanese,1.0,17533,1.0,1.0,43992.0,43993.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,None,1.0,44001.0,0.0
1,1050591,Burmese,1.0,22977,0.0,1.0,43999.0,44000.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,ISHEMIC STROKE,1.0,44002.0,0.0
2,1089472,Bangladeshi,1.0,22680,1.0,0.0,44000.0,44000.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,1.0,NSTEMI,1.0,44003.0,0.0
3,535118,Saudi Arabian,1.0,20674,1.0,1.0,43985.0,43996.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,DYSLIPEDIMIC,1.0,44002.0,0.0
4,1088965,Indian,1.0,18799,1.0,1.0,43989.0,43990.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,None,0.0,44001.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1299,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1300,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# data.dropna(inplace=True,axis=1, how='all')
data.dropna(inplace=True)

In [4]:
#fiktering the people with corona
data = data[data['COVID-19 Status \n(Positive)']==1]
data

,MRN,Nationality,Age,DATE OF BIRTH,Gender,COVID-19 Status \n(Positive),Date of Hospital Admission \nMM/DD/YYYY hh:mm,Date of ICU Admission \nMM/DD/YYYY hh:mm,Non Invasive Positive Pressure Ventilation (NIPPV),Mechanical Ventilation,...,Renal Replacement Therapy (Dialysis) in ICU,Chronic Cardiovascular-Lung Disease,Chronic Liver Kidney Disease,Diabetes,Hypertension,Any other Risk Factors or Comorbidities?,"If previous question is Yes, Specify:",ICU Outcome,Date of Outcome\nMM/DD/YYYY,ICU LOS
0,1089121,Sudanese,1.0,17533,1.0,1.0,43992.0,43993.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,None,1.0,44001.0,0.0
1,1050591,Burmese,1.0,22977,0.0,1.0,43999.0,44000.0,0.0,0.0,...,0.0,1.0,1.0,1.0,1.0,1.0,ISHEMIC STROKE,1.0,44002.0,0.0
3,535118,Saudi Arabian,1.0,20674,1.0,1.0,43985.0,43996.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,DYSLIPEDIMIC,1.0,44002.0,0.0
4,1088965,Indian,1.0,18799,1.0,1.0,43989.0,43990.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,None,0.0,44001.0,1.0
5,1089073,Syrian,1.0,16438,1.0,1.0,43993.0,43993.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,RHEUMATOID ARTHERITIS,0.0,44003.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,2055103226,Yemeni,1.0,19725,0.0,1.0,44352.0,44352.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,COVID PNEUMONIA,1.0,44361.0,1.0
1172,1079687,Burmese,1.0,25569,0.0,1.0,44353.0,44353.0,0.0,1.0,...,1.0,0.0,1.0,1.0,1.0,1.0,SEPTIC SHOCK,0.0,44361.0,0.0
1173,1118425972,SAudi Arabian,0.0,37577,1.0,1.0,44354.0,44354.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,GBS,1.0,44361.0,0.0
1175,1100337,Indonesian,0.0,30485,0.0,1.0,44355.0,44355.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,COVID PNEUMONIA,1.0,44361.0,0.0
1176,892791,Filipino,1.0,21551,0.0,1.0,44356.0,44356.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,"DKA, PNEUMONIA",1.0,44361.0,0.0

In [5]:
data.columns

Index(['MRN', 'Nationality', 'Age', 'DATE OF BIRTH', 'Gender',
       'COVID-19 Status \n(Positive)',
       'Date of Hospital Admission \nMM/DD/YYYY hh:mm',
       'Date of ICU Admission \nMM/DD/YYYY hh:mm',
       'Non Invasive Positive Pressure Ventilation (NIPPV) ',
       'Mechanical Ventilation', 'ECMO', 'HFNC', 'Received tracheostomy',
       'Prone-positioning ventilation', 'Vasopressors', 'TPE', 'Remdesivir',
       'Hydroxychloroquine', 'Antibacterial agent', 'Corticosteroid',
       'Interleukin-6 receptor antagonist',
       'Renal Replacement Therapy (Dialysis) in ICU',
       'Chronic Cardiovascular-Lung Disease', 'Chronic Liver Kidney Disease',
       'Diabetes', 'Hypertension', 'Any other Risk Factors or Comorbidities?',
       'If previous question is Yes, Specify:', 'ICU Outcome',
       'Date of Outcome\nMM/DD/YYYY', 'ICU LOS'],
      dtype='object')

In [6]:
col = [ 'Gender','Non Invasive Positive Pressure Ventilation (NIPPV) ',
       'Mechanical Ventilation', 'ECMO', 'HFNC', 'Received tracheostomy',
       'Prone-positioning ventilation', 'Vasopressors', 'TPE', 'Remdesivir',
       'Hydroxychloroquine', 'Antibacterial agent', 'Corticosteroid',
       'Interleukin-6 receptor antagonist',
       'Renal Replacement Therapy (Dialysis) in ICU',
       'Chronic Cardiovascular-Lung Disease', 'Chronic Liver Kidney Disease',
       'Diabetes', 'Hypertension', 'Any other Risk Factors or Comorbidities?']

In [7]:
x = pd.DataFrame(data , columns=col)
x = x.astype(int)
x

,Gender,Non Invasive Positive Pressure Ventilation (NIPPV),Mechanical Ventilation,ECMO,HFNC,Received tracheostomy,Prone-positioning ventilation,Vasopressors,TPE,Remdesivir,Hydroxychloroquine,Antibacterial agent,Corticosteroid,Interleukin-6 receptor antagonist,Renal Replacement Therapy (Dialysis) in ICU,Chronic Cardiovascular-Lung Disease,Chronic Liver Kidney Disease,Diabetes,Hypertension,Any other Risk Factors or Comorbidities?
0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0
1,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,1,1,1,1,1
3,1,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,1,1
4,1,0,1,0,0,0,1,1,0,0,1,1,1,0,1,0,0,0,0,0
5,1,0,1,0,1,0,1,1,0,0,1,1,1,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1171,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1
1172,0,0,1,0,0,0,1,1,0,0,0,1,1,0,1,0,1,1,1,1
1173,1,0,0,0,1,0,1,0,1,1,0,1,1,0,1,0,0,0,0,1
1175,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1
1176,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,1,1

In [8]:
y = pd.DataFrame(data , columns=['ICU Outcome'])
y = y.astype(int)
y['ICU Outcome'].value_counts()

1    116
0    111
Name: ICU Outcome, dtype: int64

In [9]:
from sklearn import model_selection
x_train,x_test,y_train,y_test = model_selection.train_test_split(x,y,test_size = 0.2,random_state=10)
print('x [features] train data', x_train.shape)
print('y [respond ] train data',y_train.shape)
print('x [features] Test data',x_test.shape)
print('y [respond ] Test data',y_test.shape)

x [features] train data (181, 20)
y [respond ] train data (181, 1)
x [features] Test data (46, 20)
y [respond ] Test data (46, 1)

In [10]:
clf = LogisticRegression().fit(x_train, y_train)
p_train = clf.predict(x_train)
acc1 = accuracy_score(y_train, p_train)
print('Accuracy score for train : {0:0.2f}'.format(acc1))

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Accuracy score for train : 0.94

In [11]:
p_test = clf.predict(x_test)
acc2 = accuracy_score(y_test, p_test)
print('Accuracy score for test : {0:0.2f}'.format(acc2))

Accuracy score for test : 1.00

In [12]:
average_precision = average_precision_score(y_train, p_train)
print('Average precision-recall score for train : {0:0.2f}'.format(average_precision))

Average precision-recall score for train : 0.93

In [13]:
average_precision = average_precision_score(y_test, p_test)
print('Average precision-recall score fro test : {0:0.2f}'.format(average_precision))

Average precision-recall score fro test : 1.00

In [14]:
y_test['predicted value']= p_test

y_test.replace(1.0,'Yes',inplace=True)
y_test.replace(0.0,'No',inplace=True)

y_test

<ipython-input-14-98dda316b881>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y_test['predicted value']= p_test
C:\Users\dell\anaconda3\lib\site-packages\pandas\core\frame.py:4379: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

     ICU Outcome predicted value
239           No              No
72            No              No
207           No              No
184          Yes             Yes
216           No              No
597          Yes             Yes
1107          No              No
173           No              No
185          Yes             Yes
1170         Yes             Yes
408          Yes             Yes
1027          No              No
311           No              No
276           No              No
383          Yes             Yes
1175         Yes             Yes
166           No              No
223           No              No
308          Yes             Yes
307           No              No
147          Yes             Yes
916          Yes             Yes
1102         Yes             Yes
455          Yes             Yes
606          Yes             Yes
1153         Yes             Yes
68            No              No
176           No              No
92           Yes             Yes
45            No              No
1077         Yes             Yes
1053          No              No
771           No              No
135           No              No
888           No              No
553           No              No
1068          No              No
386           No              No
174          Yes             Yes
974          Yes             Yes
46            No              No
451           No              No
7             No              No
1071         Yes             Yes
187           No              No
496           No              No

In [15]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='accuracy')

print("Accuracy scores:\n", scores)
print(scores.mean())

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Accuracy scores:
 [0.80434783 0.89130435 0.95555556 0.91111111 0.91111111]
0.8946859903381643

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [19]:
from sklearn.model_selection import cross_val_score

# # Multiply by -1 since sklearn calculates *negative* MAE
scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='accuracy')

print("Accuracy scores:\n", scores)
print('average accuracy :',scores.mean())

scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='precision')

print("precision scores:\n", scores)
print('average accuracy :',scores.mean())


scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='recall')

print("recall scores:\n", scores)
print('average accuracy :',scores.mean())

scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='f1')

print("f1 scores:\n", scores)
print('average accuracy :',scores.mean())

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Accuracy scores:
 [0.80434783 0.89130435 0.95555556 0.91111111 0.91111111]
average accuracy : 0.8946859903381643
precision scores:
 [0.85714286 0.875      0.95652174 0.95238095 0.91304348]
average accuracy : 0.9108178053830228
recall scores:
 [0.75       0.91304348 0.95652174 0.86956522 0.91304348]
average accuracy : 0.8804347826086957
f1 scores:
 [0.8        0.89361702 0.95652174 0.90909091 0.91304348]
average accuracy : 0.8944546295517618

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [20]:
from sklearn.model_selection import cross_val_score

# # Multiply by -1 since sklearn calculates *negative* MAE
scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='accuracy')

print("Accuracy scores:\n", scores)
print('average accuracy :',scores.mean())

scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='precision')

print("precision scores:\n", scores)
print('average precision :',scores.mean())


scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='recall')

print("recall scores:\n", scores)
print('average recall :',scores.mean())

scores = cross_val_score(clf.fit(x, y), x, y,
                              cv=5,
                              scoring='f1')

print("f1 scores:\n",scores)
print('average f1 :',scores.mean())

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

Accuracy scores:
 [0.80434783 0.89130435 0.95555556 0.91111111 0.91111111]
average accuracy : 0.8946859903381643
precision scores:
 [0.85714286 0.875      0.95652174 0.95238095 0.91304348]
average precision : 0.9108178053830228
recall scores:
 [0.75       0.91304348 0.95652174 0.86956522 0.91304348]
average recall : 0.8804347826086957
f1 scores:
 [0.8        0.89361702 0.95652174 0.90909091 0.91304348]
average f1 : 0.8944546295517618

C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)
C:\Users\dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)